//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PARIS2008.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cactus
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cactus()
        {
            this.Cactus_Exhibition = new HashSet<Cactus_Exhibition>();
        }
    
        public int id_Cactus { get; set; }
        public int id_Vid { get; set; }
        public int id_Origin { get; set; }
        public Nullable<int> Age_InYears { get; set; }
        public Nullable<int> Price { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cactus_Exhibition> Cactus_Exhibition { get; set; }
        public virtual Origin Origin { get; set; }
        public virtual Vid_Cactus Vid_Cactus { get; set; }
    }
}
