//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PARIS2008.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cactus_Exhibition
    {
        public int id_Cactus_Exhibition { get; set; }
        public Nullable<int> id_Cactus { get; set; }
        public Nullable<int> id_Exhibition { get; set; }
    
        public virtual Cactus Cactus { get; set; }
        public virtual Exhibition Exhibition { get; set; }
    }
}
